In [10]:
import evo
import numpy as np
import evo.core.lie_algebra as lie
from evo.core import trajectory
from evo.tools import plot, file_interface, log
import copy
import numpy as np

import matplotlib.pyplot as plt
root_path = '/home/dj/Documents/new_lung_exp/vo/calibration/'

param_list = []

for i in range(2):

    gt_file = root_path + 'traj_gt_S055_%s.txt' % i
    est_file = root_path + 'LOFTR_traj_est_S055_%s.txt' % i

    traj_ref = file_interface.read_tum_trajectory_file(gt_file)
    traj_est = file_interface.read_tum_trajectory_file(est_file)

    traj_est_aligned_scaled = copy.deepcopy(traj_est)
    param = traj_est_aligned_scaled.align(traj_ref, correct_scale=True)
    param_list += [param]

In [11]:
print(param_list[0])

def print_param(param_list):
    for i in range(len(param_list)):
        pass
    pass

(array([[-0.27330463,  0.42188546, -0.86447513],
       [-0.71002427, -0.69478948, -0.11459978],
       [-0.6489762 ,  0.58247767,  0.48943809]]), array([ 0.02100043, -0.00521101,  0.03950659]), 0.5589157145949386)


In [12]:
param_list[1]

(array([[ 0.47379374,  0.6516939 , -0.592296  ],
        [-0.8806326 ,  0.34879223, -0.3206715 ],
        [-0.00239142,  0.67352732,  0.73915846]]),
 array([ 0.01572858, -0.0116035 ,  0.01469639]),
 0.7092234553988693)